### ISSUE TITLE
залей полный исходник

### ISSUE THREAD

**Issue by dearnek20** [alexsprokosin/Economy-Simulator-Russia#1]
![image](https://github.com/user-attachments/assets/458c29b4-ce92-41a0-aefe-892bbf60b8e8)
 
![image](https://github.com/user-attachments/assets/6bb70311-4bf2-4877-bf12-693c8d5b9468)

**Comment by alexsprokosin** [comment]
ох, спасибо то что заметил

**Comment by alexsprokosin** [comment]
добавил
