### ISSUE TITLE
залей исходник

### ISSUE THREAD

**Issue by iShowVova** [alexsprokosin/Economy-Simulator-Russia#3]
нету файла appsettings.examplare.json залей полный исходник пж ты прост мне в вк в группу скинул теперь не пойму нечего еще ошибка при миграции файлов(когда спросишь скину команду чтоб ты понял) а без этой миграции не запустится сайт и вообще нечего что то непонятно скажи ок?

**Comment by alexsprokosin** [comment]
Видимо когда я заливал файлы, гит хаб удалил часть файлов, щас восстановлю файл и перепроверю все ли файлы есть.

**Comment by iShowVova** [comment]
ок когда будет готово закрой

**Comment by iShowVova** [comment]
когда будешь восстанавливать файлы?

**Comment by alexsprokosin** [comment]
всё добавил

**Comment by iShowVova** [comment]
спс
